blank_issues_enabled: false
contact_links:
  - name: NINA Discord
    url: https://discord.gg/nighttime-imaging-n-astronomy-244681146296762369
    about: Get help with NINA and advanced sequencing from the community
